FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

RUN apt-get install -y --no-install-recommends \
        build-essential \
        python-dev \
        libssl-dev \
        libmysqlclient-dev \
        libxslt1-dev \
        libffi-dev \
        libyaml-dev \
        pkg-config \
        git \
    && apt-get clean

COPY pip.conf /tmp/pip.conf

RUN curl -o /tmp/constraints.txt https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt \
    && pip --no-cache-dir install -U virtualenv \
    && virtualenv /var/lib/microservices/venv \
    && mv /tmp/constraints.txt /var/lib/microservices/venv \
    && mv /tmp/pip.conf /var/lib/microservices/venv \
    && /var/lib/microservices/venv/bin/pip install --upgrade \
        Babel \
        Flask \
        Jinja2 \
        Mako \
        MarkupSafe \
        Paste \
        PasteDeploy \
        PyYAML \
        Routes \
        SQLAlchemy \
        Tempita \
        WebOb \
        alembic \
        amqp \
        anyjson \
        appdirs \
        cachetools \
        castellan \
        cliff \
        cmd2 \
        contextlib2 \
        debtcollector \
        decorator \
        enum34 \
        eventlet \
        fasteners \
        funcsigs \
        functools32 \
        futures \
        futurist \
        greenlet \
        iso8601 \
        jinja2 \
        jsonpatch \
        jsonpointer \
        jsonschema \
        keystoneauth1 \
        keystonemiddleware \
        kombu \
        monotonic \
        msgpack-python \
        netaddr \
        netifaces \
        os-client-config \
        oslo.concurrency \
        oslo.config \
        oslo.context \
        oslo.db \
        oslo.i18n \
        oslo.log \
        oslo.messaging \
        oslo.middleware \
        oslo.policy \
        oslo.serialization \
        oslo.service \
        oslo.utils \
        paramiko \
        pbr \
        pika \
        pika-pool \
        positional \
        prettytable \
        pycadf \
        pycrypto \
        pyinotify \
        pymemcache \
        pymysql \
        pyparsing \
        python-barbicanclient \
        python-ceilometerclient \
        python-cinderclient \
        python-congressclient \
        python-dateutil \
        python-designateclient \
        python-editor \
        python-glanceclient \
        python-heatclient \
        python-ironicclient \
        python-keystoneclient \
        python-magnumclient \
        python-manilaclient \
        python-memcached \
        python-mistralclient \
        python-muranoclient \
        python-neutronclient \
        python-novaclient \
        python-openstackclient \
        python-saharaclient \
        python-swiftclient \
        python-troveclient \
        python-tuskarclient \
        python-zaqarclient \
        pytz \
        repoze.lru \
        requests \
        requestsexceptions \
        retrying \
        simplejson \
        six \
        sqlalchemy-migrate \
        sqlparse \
        stevedore \
        tooz \
        unicodecsv \
        warlock \
        wrapt \
    && rm -rf requirements

ENV PATH /var/lib/microservices/venv/bin:$PATH
